Memory-Name: "Memory"
MySQL:
  Host: "localhost"
  Port: 3306
  Username: "root"
  Password: "minecraft"
  Database: "Memory"
  DummyData:
    Display: Sending a dummy Data to prevent MySQL Timed out!
    SendRate: 300

Levels:
  1:
    #Display name of this level
    Display: "Level 1"
    #Regeneration Time per 1 Energy (Seconds)
    Regen-Time: 480
    #Maximum Capacity of this Level
    Max-Energy: 64
  2:
    Display: "Level 2"
    Regen-Time: 480
    Max-Energy: 128
  3:
    Display: "Level 3"
    Regen-Time: 480
    Max-Energy: 256

General:
  Pattern: "d MMMM YYYY HH:mm:ss"
  Language: "th"
  Country: "TH"

Messages:
  Prefix: "&7<GRADIENT:2FFFD3>[Memory]</GRADIENT:F6FF43>&r "
  MySQL:
    Connecting: "&aConnecting to MySQL server."
    Connected: "&aConnected to MySQL server."
    Error: "&4Could not connect to MySQL server. Disabling plugin. . ."
  Info:
    #Avaiable Placeholders:
    # PlaceholderAPIs
    # <memory> - Player's current memory
    # <max_memory> - Player's Max Memory
    # <one_regenerate_time> - Time it take to regenerate 1 memory (in datetime)
    # <one_regenerate_seconds> - Time it take to regenerate 1 memory (in seconds)
    # <one_regenerate_second> - Time it take to regenerate 1 memory (in seconds left from minute)
    # <one_regenerate_minute> - Time it take to regenerate 1 memory (in minutes left from hour)
    # <one_regenerate_hour> - Time it take to regenerate 1 memory (in hours)
    # <full_regenerate_time> - Time it take to regenerate all memory (in datetime)
    # <full_regenerate_seconds> - Time it take to regenerate all memory (in seconds)
    # <full_regenerate_second> - Time it take to regenerate all memory (in seconds left from minute)
    # <full_regenerate_minute> - Time it take to regenerate all memory (in minutes left from hour)
    # <full_regenerate_hour> - Time it take to regenerate all memory (in hours)
    # <player_multiplier> - Player's booster multiplier
    # <player_duration> - Player's booster duration (in seconds)
    # <player_end_time> - Player's booster end time (in datetime)
    # <player_end_second> - Player's booster end time (in seconds)
    # <server_multiplier> - Server's booster multiplier
    # <server_duration> - Server's booster duration (in seconds)
    # <server_end_time> - Server's booster end time (in datetime)
    # <server_end_second> - Server's booster end time (in seconds)
    # <bypass_end_time> - Player's bypass end time (in datetime)
    # <bypass_duration> - Player's bypass duration (in seconds)
    Info:
      - " "
      - "&b✦ <SOLID:66FFCC>You currently have <SOLID:18A774><memory> <SOLID:66FFCC>Memory"
      - "<HIDE_WHEN_0>"
      - "<HIDE_WHEN_0>&e⌛ &7Your memory will recovered once at &f<one_regenerate_time> &8(or in <one_regenerate_seconds> seconds)"
      - "<HIDE_WHEN_0>&c⏳ &7Your memory will fully recovered at &f<full_regenerate_time> &8(or in <full_regenerate_seconds> seconds)"
      - " "
      - "<player_boost>"
      - " "
      - "<server_boost>"
      - " "
      - "<bypass>"
    Player_Boost:
      Avaiable:
        - "&a⏏ <SOLID:FDF9A3>You currently have <SOLID:FDA769><player_multiplier>x <SOLID:FDF9A3>Boost for <SOLID:FDA769><player_duration>s"
        - "&c▬ <SOLID:FF8686>This boost will end at <SOLID:FF7EF2><player_end_time> &c(or in <player_end_second> seconds)"
      Not-Avaiable:
        - "&8☁ &7You currently not have player boost activate."
    Server_Boost:
      Avaiable:
        - "&e★ <SOLID:B9F7FF>You currently have <SOLID:9A97FF><server_multiplier>x <SOLID:B9F7FF>of Global Boost for <SOLID:9A97FF><server_duration>s"
        - "&c▬ <SOLID:FF8686>This boost will end at <SOLID:FF7EF2><server_end_time> &c(or in <server_end_second> seconds)"
      Not-Avaiable:
        - "&8☁ &7The server is now currently not have any boost active at this time."
    Bypass:
      Avaiable:
        - "&a✦ <SOLID:66FFCC>You currently have <SOLID:18A774><bypass_duration>s <SOLID:66FFCC>of Bypass left &c(end at <bypass_end_time>)"
      Not-Avaiable:
        - "&8☁ &7You currently not have bypass activate."
    Global_Boost_End: "&c▬ <SOLID:FF8686>The global Memory Boost is now ended."
    Global_Boost_Start: "&e★ <SOLID:B9F7FF>The global Memory Boost is now activated at rate <SOLID:9A97FF><multiplier>x <SOLID:B9F7FF>for <SOLID:9A97FF><duration>s"
    Player_Boost_End: "&c▬ <SOLID:FF8686>Your Memory Booster is now ended."
    Player_Boost_Start: "&a⏏ <SOLID:FDF9A3>Your Memory <SOLID:FDA769><multiplier>x <SOLID:FDF9A3>Booster is now activated for <SOLID:FDA769><duration>s."
    Bypass_Start: "&a✦ <SOLID:66FFCC>Your Memory Bypass is now activated for <SOLID:18A774><duration>s"
    Bypass_End: "&c▬ <SOLID:FF8686>Your Memory Bypass is now ended."

  Command:
    invalid-arguments: "<GRADIENT:66FFCC>Invalid Arguments! please try again.</GRADIENT:FF0080>"
    Help:
      - "<GRADIENT:028A97>Memory System Help Menu:</GRADIENT:18A774>"
      - "  <GRADIENT:FF7EF2>/memory upgrade <player> <multiplier> <value></GRADIENT:9A97FF>"
      - "    <GRADIENT:FF8686>Upgrade the player's Capacity/Regeneration Level</GRADIENT:028A97>"
      - "  <GRADIENT:FF7EF2>/memory set <player> <multiplier> <value></GRADIENT:9A97FF>"
      - "    <GRADIENT:FF8686>Set player's Capacity/Regeneration Level or Current Capacity</GRADIENT:028A97>"
      - "  <GRADIENT:FF7EF2>/memory give <player> <value> [Update Regeneration Time]</GRADIENT:9A97FF>"
      - "    <GRADIENT:FF8686>Give player's Memory (can be negative)</GRADIENT:028A97>"
      - "  <GRADIENT:FF7EF2>/memory boost player <player> <multiplier> <duration></GRADIENT:9A97FF>"
      - "    <GRADIENT:FF8686>Set specific player's boosting state</GRADIENT:028A97>"
      - "  <GRADIENT:FF7EF2>/memory boost server <multiplier> <duration></GRADIENT:9A97FF>"
      - "    <GRADIENT:FF8686>Set the global boost</GRADIENT:028A97>"
      - "  <GRADIENT:FF7EF2>/memory boost stop player <player></GRADIENT:9A97FF>"
      - "    <GRADIENT:FF8686>Stop the specific player's boost state</GRADIENT:028A97>"
      - "  <GRADIENT:FF7EF2>/memory boost stop server</GRADIENT:9A97FF>"
      - "    <GRADIENT:FF8686>Stop the global boost</GRADIENT:028A97>"
      - "  <GRADIENT:FF7EF2>/memory setBypass <player> <duration></GRADIENT:9A97FF>"
      - "    <GRADIENT:FF8686>Set the Bypass state of the player</GRADIENT:028A97>"
      - "  <GRADIENT:FF7EF2>/memory stopBypass <player></GRADIENT:9A97FF>"
      - "    <GRADIENT:FF8686>Stop the Bypass state of specific player</GRADIENT:028A97>"
      - "  <GRADIENT:FF7EF2>/memory reload</GRADIENT:9A97FF>"
      - "    <GRADIENT:FF8686>Reload the configuration</GRADIENT:028A97>"
      - "  <GRADIENT:FF7EF2>/memory help</GRADIENT:9A97FF>"
      - "    <GRADIENT:FF8686>Open this Menu</GRADIENT:028A97>"
    Upgrade:
      invalid-player: "<GRADIENT:FF0080>Invalid Arguments: [Player] does not exists/online.</GRADIENT:FF0000>"
      invalid-modifier: "<GRADIENT:FF0080>Invalid Arguments: [Modifier] does not exists.</GRADIENT:FF0000>"
      invalid-value: "<GRADIENT:FF0080>Invalid Arguments: [Value] does not valid.</GRADIENT:FF0000>"
      feedback: "<GRADIENT:66FFCC>Successfully upgraded <player>'s <modifier></GRADIENT:028A97>"
    Set:
      invalid-player: "<GRADIENT:FF0080>Invalid Arguments: [Player] does not exists/online.</GRADIENT:FF0000>"
      invalid-modifier: "<GRADIENT:FF0080>Invalid Arguments: [Modifier] does not exists.</GRADIENT:FF0000>"
      invalid-value: "<GRADIENT:FF0080>Invalid Arguments: [Value] does not valid.</GRADIENT:FF0000>"
      feedback: "<GRADIENT:66FFCC>Successfully set <player>'s <modifier> to <value></GRADIENT:028A97>"
    Give:
      invalid-player: "<GRADIENT:FF0080>Invalid Arguments: [Player] does not exists/online.</GRADIENT:FF0000>"
      invalid-value: "<GRADIENT:FF0080>Invalid Arguments: [Value] does not valid.</GRADIENT:FF0000>"
      feedback: "<GRADIENT:66FFCC>Successfully modified <player>'s Memory to <value></GRADIENT:028A97>"
    Boost:
      invalid-player: "<GRADIENT:FF0080>Invalid Arguments: [Player] does not exists/online.</GRADIENT:FF0000>"
      invalid-multiplier: "<GRADIENT:FF0080>Invalid Arguments: [Multiplier] or [Duration] does not valid.</GRADIENT:FF0000>"
      feedback-player: "<GRADIENT:66FFCC>Successfully set <player>'s booster to <multiplier>x for <duration> seconds</GRADIENT:028A97>"
      feedback-server: "<GRADIENT:66FFCC>Successfully set Global Boost to <multiplier>x for <duration> seconds</GRADIENT:028A97>"
      feedback-stop-player: "<GRADIENT:66FFCC>Successfully stop the Boost state of <player></GRADIENT:028A97>"
      feedback-stop-server: "<GRADIENT:66FFCC>Successfully stop the Boost state of the server</GRADIENT:028A97>"
    SetBypass:
      invalid-player: "<GRADIENT:FF0080>Invalid Arguments: [Player] does not exists/online.</GRADIENT:FF0000>"
      invalid-duration: "<GRADIENT:FF0080>Invalid Arguments: [Duration] does not valid.</GRADIENT:FF0000>"
      feedback: "<GRADIENT:66FFCC>Successfully set Bypass state of <player> to</GRADIENT:028A97> <SOLID:00FF00>True<GRADIENT:66FFCC> for <duration> seconds</GRADIENT:028A97>"
    StopBypass:
      invalid-player: "<GRADIENT:FF0080>Invalid Arguments: [Player] does not exists/online.</GRADIENT:FF0000>"
      feedback: "<GRADIENT:66FFCC>Successfully set Bypass state of <player> to</GRADIENT:028A97> <SOLID:FF0000>False"
    Reload:
      feedback: "<GRADIENT:66FFCC>Successfully reloaded the Configuration Files.</GRADIENT:028A97> &e(<ms>ms)"
